name: Semantic Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    name: Run Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false
        env:
          GH_TOKEN: ${{ secrets.SM_RELEASE}}
          GITHUB_TOKEN: ${{ secrets.VERAN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.SM_RELEASE}}
          GITHUB_TOKEN: ${{ secrets.VERAN }}
        run: npx semantic-release
